spring:
  application:
    name: TransDoc
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
    office-home: /opt/libreoffice25.2
    working-dir: /DATA/shared_files
logging:
  config: /DATA/WEB/API/config/logback-spring.xml
  level:
    org.jodconverter: DEBUG