spring:
  application:
    name: TransDoc
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
    office-home: /Applications/LibreOffice.app/Contents
    template-profile-dir: /Users/jaewon/Downloads/jodconverter-profile-template
    working-dir: /Users/jaewon/upload
logging:
  level:
    org.jodconverter: DEBUG