spring:
  application:
    name: TransDoc
jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
    office-home: /usr/lib64/libreoffice
logging:
  level:
    org.jodconverter: DEBUG