spring:
  application:
    name: TransDoc
jodconverter:
  remote:
    enabled: true
    url: http://localhost:2002
    socket-timeout: 300000
    connect-timeout: 300000
logging:
  level:
    org.jodconverter: DEBUG